package Views;

import BusinessObjects.Chat;
import BusinessObjects.Message;
import BusinessObjects.User;
import Control.ChatControl;
import Control.MessageControl;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 * @author Juan Enrique Solis Perla
 * @ID: 165920 Advanced Databases Class, ISW, ITSON
 */
public class ChatForm extends javax.swing.JFrame implements ActionListener {

    private Chat chat;
    private User user;
    private ChatControl chatControl;
    private MessageControl messageControl;
    private ArrayList<Message> chatMessages = null;

    public ChatForm(Chat chat, User userHost, User userReceiver) {
        initComponents();
        setVisible(true);
        this.setTitle(userHost.getUserName());

        this.chatControl = new ChatControl();
        this.messageControl = new MessageControl();
        this.user = userHost;
        this.chat = chat;

        jButtonSend.addActionListener(this);
        jButtonSend.setActionCommand("Send");

        jButtonRefresh.addActionListener(this);
        jButtonRefresh.setActionCommand("Refresh");

        chatMessages = messageControl.findAllByChatID(chat.getId());
        refreshJTextPaneChatMessages();
        jLabelTitle.setText("Chat with " + userReceiver.getUserName());
    }

    private void send() {
        String messageText = jTextAreaMessage.getText();
        Message message = new Message(new Date(), messageText, this.user, this.chat);
        messageControl.save(message);
        getChatMessages();
        refreshJTextPaneChatMessages();
        jTextAreaMessage.setText("");
    }

    private void refreshPane() {
        getChatMessages();
        refreshJTextPaneChatMessages();
    }

    private void getChatMessages() {
        chatMessages.clear();
        chatMessages = messageControl.findAllByChatID(chat.getId());
    }

    private void refreshJTextPaneChatMessages() {
        Style style1 = jTextPaneChat.addStyle("User1Style", null);
        StyleConstants.setForeground(style1, Color.BLUE);

        Style style2 = jTextPaneChat.addStyle("User2Style", null);
        StyleConstants.setForeground(style2, Color.MAGENTA);

//        StyledDocument doc = jTextPaneChat.getStyledDocument();
        StyledDocument doc = new DefaultStyledDocument();

        if (chatMessages.size() > 0) {
            for (Message m : chatMessages) {
                try {
                    if (m.getUser().getId() == this.user.getId()) {
                        doc.insertString(doc.getLength(), m.getUser().getUserName() + ": ", style1);
                        doc.insertString(doc.getLength(), m.getMessage() + "\n\n", null);
                    } else {
                        doc.insertString(doc.getLength(), m.getUser().getUserName() + ": ", style2);
                        doc.insertString(doc.getLength(), m.getMessage() + "\n\n", null);
                    }
                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            }
            jTextPaneChat.setStyledDocument(doc);
        }
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        String action = ae.getActionCommand();

        switch (action) {

            case "Send":
                send();
                break;

            case "Refresh":
                refreshPane();
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jScrollPaneChat = new javax.swing.JScrollPane();
        jTextPaneChat = new javax.swing.JTextPane();
        jScrollPaneMessage = new javax.swing.JScrollPane();
        jTextAreaMessage = new javax.swing.JTextArea();
        jButtonSend = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();

        setResizable(false);

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitle.setText("Chat with Juan");

        jTextPaneChat.setEditable(false);
        jTextPaneChat.setBackground(new java.awt.Color(204, 204, 204));
        jTextPaneChat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPaneChat.setViewportView(jTextPaneChat);

        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setRows(5);
        jScrollPaneMessage.setViewportView(jTextAreaMessage);

        jButtonSend.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSend.setText("Send");

        jButtonRefresh.setText("Refresh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneChat)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRefresh))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPaneMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTitle)
                    .addComponent(jButtonRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneChat, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSend, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(jScrollPaneMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPaneChat;
    private javax.swing.JScrollPane jScrollPaneMessage;
    private javax.swing.JTextArea jTextAreaMessage;
    private javax.swing.JTextPane jTextPaneChat;
    // End of variables declaration//GEN-END:variables
}
